export const API_URL=import.meta.env.VITE_API_URL||'http://localhost:3000/api';
let csrfToken=sessionStorage.getItem('admin-csrf')||'';
export type ApiUser={email:string;name:string;role:string;permissions:readonly string[];mustChangePassword:boolean};
export class ApiError extends Error{status:number;constructor(status:number,message:string){super(message);this.status=status}}
async function request<T>(path:string,options:RequestInit={}){const headers=new Headers(options.headers);if(options.body&&!(options.body instanceof FormData))headers.set('Content-Type','application/json');if(!['GET','HEAD'].includes(options.method||'GET')&&csrfToken)headers.set('X-CSRF-Token',csrfToken);const response=await fetch(`${API_URL}${path}`,{...options,headers,credentials:'include'});const payload=await response.json().catch(()=>({}));if(!response.ok){const message=Array.isArray(payload.message)?payload.message.join('. '):payload.message||payload.error||'Request failed';throw new ApiError(response.status,message)}return payload as T}
export const api={
  staff:<T>()=>request<T>('/admin/staff'),
  createStaff:<T>(data:unknown)=>request<T>('/admin/staff',{method:'POST',body:JSON.stringify(data)}),
  updateStaff:<T>(id:string,data:unknown)=>request<T>(`/admin/staff/${id}`,{method:'PATCH',body:JSON.stringify(data)}),
  productionIntake:<T>()=>request<T>('/admin/orders/production/intake'),
  async login(email:string,password:string){const result=await request<{csrfToken:string;user:ApiUser}>('/auth/login',{method:'POST',body:JSON.stringify({email,password})});csrfToken=result.csrfToken;sessionStorage.setItem('admin-csrf',csrfToken);return result.user},
  async me(){const result=await request<{csrfToken:string;user:ApiUser}>('/auth/me');csrfToken=result.csrfToken;sessionStorage.setItem('admin-csrf',csrfToken);return result.user},
  async logout(){await request('/auth/logout',{method:'POST'});csrfToken='';sessionStorage.removeItem('admin-csrf')},
  async changePassword(currentPassword:string,newPassword:string){await request('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})});csrfToken='';sessionStorage.removeItem('admin-csrf')},
  products:<T>()=>request<T>('/admin/products'),createProduct:<T>(data:unknown)=>request<T>('/admin/products',{method:'POST',body:JSON.stringify(data)}),updateProduct:<T>(id:string,data:unknown)=>request<T>(`/admin/products/${id}`,{method:'PATCH',body:JSON.stringify(data)}),deleteProduct:(id:string)=>request(`/admin/products/${id}`,{method:'DELETE'}),
  quotes:<T>()=>request<T>('/admin/quotes'),updateQuoteStatus:<T>(id:string,status:string)=>request<T>(`/admin/quotes/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}),
  orders:<T>()=>request<T>('/admin/orders'),createOrder:<T>(data:unknown)=>request<T>('/admin/orders',{method:'POST',body:JSON.stringify(data)}),productionJobs:<T>()=>request<T>('/admin/orders/production/jobs'),productionJobActivity:<T>(id:string)=>request<T>(`/admin/orders/production/jobs/${id}/activity`),addProductionJobNote:<T>(id:string,note:string)=>request<T>(`/admin/orders/production/jobs/${id}/activity`,{method:'POST',body:JSON.stringify({note})}),releaseOrder:<T>(id:string)=>request<T>(`/admin/orders/${id}/release`,{method:'POST'}),updateProductionJob:<T>(id:string,data:unknown)=>request<T>(`/admin/orders/production/jobs/${id}`,{method:'PATCH',body:JSON.stringify(data)}),updateOrderStatus:<T>(id:string,status:string,note='',customerVisible=true)=>request<T>(`/admin/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status,note,customerVisible})}),
  adjustStock:<T>(id:string,stock:number,reason:string)=>request<T>(`/admin/products/${id}/stock`,{method:'POST',body:JSON.stringify({stock,reason})}),
  dashboard:<T>()=>request<T>('/admin/dashboard'),activity:<T>()=>request<T>('/admin/activity'),stockActivity:<T>()=>request<T>('/admin/stock-activity'),insights:<T>()=>request<T>('/admin/insights'),settings:<T>()=>request<T>('/admin/settings'),updateSettings:<T>(data:unknown)=>request<T>('/admin/settings',{method:'PATCH',body:JSON.stringify(data)}),
  payments:<T>()=>request<T>('/admin/payments'),paymentSummary:<T>()=>request<T>('/admin/payments/summary'),
  pricingRules:<T>()=>request<T>('/admin/pricing/rules'),savePricingDraft:<T>(id:string,data:unknown)=>request<T>(`/admin/pricing/rules/${id}/draft`,{method:'PATCH',body:JSON.stringify(data)}),testPricingDraft:<T>(id:string,data:unknown)=>request<T>(`/admin/pricing/drafts/${id}/test`,{method:'POST',body:JSON.stringify(data)}),publishPricingDraft:<T>(id:string)=>request<T>(`/admin/pricing/drafts/${id}/publish`,{method:'POST'}),pricingHistory:<T>(id:string)=>request<T>(`/admin/pricing/rules/${id}/history`),
  async upload(file:File){const body=new FormData();body.append('file',file);return request<{url:string}>('/admin/media',{method:'POST',body})}
};
