import React,{useEffect,useRef,useState} from 'react';
import {Plus,Trash2,ArrowLeft,Printer,Search,RefreshCw} from 'lucide-react';
import {api} from './api';
import type {PricingRule} from './PricingStudio';
const money=(p:number)=>'GH₵ '+(p/100).toFixed(2);
const errorText=(e:unknown)=>e instanceof Error?e.message:'Unable to complete this action';
const key=()=>crypto.randomUUID();
type Product={id:string;name:string;price:number;stock:number;status:string};
type Order={id:string;orderNumber:string;customerName:string;customerEmail:string;customerPhone:string;source:string;status:string;paymentStatus:string;totalPesewas:number;requiresReview:boolean;createdAt:string};
type Detail=Order & {collectedPesewas:number;refundedPesewas:number;refundablePesewas:number;outstandingPesewas:number;netCollectedPesewas:number;customerNote:string;items:{id:string;name:string;kind:string;quantity:number;unitPricePesewas:number;totalPesewas:number;specification:string}[];payments:{id:string;amountPesewas:number;provider:string;externalReference:string;status:string;paidAt:string}[];refunds:{id:string;amountPesewas:number;method:string;externalReference:string;reason:string;occurredAt:string}[];history:{id:string;note:string;createdAt:string}[]};
type Line={key:string;type:'large_format'|'product'|'custom';serviceCode:string;productId:string;name:string;width:string;height:string;unit:'ft'|'in';quantity:string;needsDesign:boolean;designFee:string;unitPrice:string;description:string;artworkUrl:string;artworkName:string};
const line=(rules:PricingRule[]):Line=>({key:key(),type:'large_format',serviceCode:rules[0]?.code||'',productId:'',name:'',width:'',height:'',unit:'ft',quantity:'1',needsDesign:false,designFee:'100',unitPrice:'',description:'',artworkUrl:'',artworkName:''});
function CounterForm({rules,products,onCreated,onCancel}:{rules:PricingRule[];products:Product[];onCreated:(id:string)=>void;onCancel:()=>void}){
  const [form,setForm]=useState({customerName:'',customerEmail:'',customerPhone:'',source:'walk_in',salesperson:'',fulfilmentMethod:'pickup',deliveryAddress:'',deliveryLandmark:'',deliveryFee:'0',requestedDate:'',customerNote:'',artworkOption:'later',artworkLink:''});
  const [lines,setLines]=useState<Line[]>([line(rules)]),[estimate,setEstimate]=useState<{totalPesewas:number;requiresReview:boolean;lines:{name:string;totalPesewas:number}[]}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[requestKey,setRequestKey]=useState(key);
  const [estimateInput,setEstimateInput]=useState('');
  // deliveryFee is a UI-only text field; the API takes pesewas and rejects
  // unknown properties, so it must not travel with the rest of the form.
  const body=()=>{const {deliveryFee:_deliveryFee,...rest}=form;return ({...rest,customerPhone:form.customerPhone||undefined,requestKey,deliveryFeePesewas:form.fulfilmentMethod==='delivery'?Math.round(Number(form.deliveryFee)*100):0,items:lines.map(l=>({type:l.type,quantity:Number(l.quantity),...(l.type==='large_format'?{serviceCode:l.serviceCode,width:Number(l.width),height:Number(l.height),unit:l.unit,needsDesign:l.needsDesign,designFeePesewas:l.needsDesign?Math.round(Number(l.designFee)*100):undefined}:l.type==='product'?{productId:l.productId}:{name:l.name,unitPricePesewas:l.unitPrice?Math.round(Number(l.unitPrice)*100):undefined,description:l.description}),...(l.artworkUrl?{artworkUrl:l.artworkUrl,artworkName:l.artworkName}:{})}))});};
  const currentInput=JSON.stringify(body());const validEstimate=estimate&&estimateInput===currentInput;
  const update=(k:string,value:Partial<Line>)=>setLines(ls=>ls.map(l=>l.key===k?{...l,...value}:l));
  async function review(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const result=await api.staffEstimate<NonNullable<typeof estimate>>(body());setEstimate(result);setEstimateInput(currentInput);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function create(){setBusy(true);setError('');try{const r=await api.createOrder<{id:string}>(body());onCreated(r.id);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function upload(id:string,file?:File){if(!file)return;setUploading(true);setError('');try{const r=await api.uploadArtwork(file);update(id,{artworkUrl:r.url,artworkName:file.name});}catch(e){setError(errorText(e));}finally{setUploading(false);}}
  return <form className="counter-workspace" onSubmit={review}><div className="section-title"><div><span className="eyebrow">COUNTER / NEW ORDER</span><h2>Let’s get the details right.</h2><p>Add every item, review the price, then record payment.</p></div><button type="button" className="button ghost" onClick={onCancel}>Cancel</button></div>
    {error&&<p className="alert" role="alert">{error}</p>}
    <fieldset disabled={busy||uploading}><section className="surface counter-section"><h3><span>01</span> Customer & order</h3><div className="form-grid three">
      <label>Customer name<input required minLength={2} value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/></label>
      <label>Phone<input type="tel" required={!form.customerEmail} value={form.customerPhone} onChange={e=>setForm({...form,customerPhone:e.target.value})}/></label>
      <label>Email · optional<input type="email" value={form.customerEmail} onChange={e=>setForm({...form,customerEmail:e.target.value})}/><small>For email receipts and online tracking.</small></label>
      <label>Order source<select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}><option value="walk_in">Walk-in</option><option value="salesperson">Salesperson</option></select></label>
      {form.source==='salesperson'&&<label>Salesperson name<input required value={form.salesperson} onChange={e=>setForm({...form,salesperson:e.target.value})}/></label>}
      <label>Needed by<input type="date" value={form.requestedDate} onChange={e=>setForm({...form,requestedDate:e.target.value})}/></label>
    </div></section>
    <section className="surface counter-section"><h3><span>02</span> Items & artwork</h3>{lines.map((l,i)=><article className="counter-line" key={l.key}><div className="counter-line-heading"><strong>Item {String(i+1).padStart(2,'0')}</strong><button className="button ghost" type="button" disabled={lines.length===1} onClick={()=>setLines(lines.filter(x=>x.key!==l.key))} aria-label={`Remove item ${i+1}`}><Trash2 size={16}/>Remove</button></div>
      <div className="form-grid three"><label>Item type<select value={l.type} onChange={e=>update(l.key,{type:e.target.value as Line['type']})}><option value="large_format">Large-format print</option><option value="product">Shop product</option><option value="custom">Custom service / manual quote</option></select></label>
      {l.type==='large_format'?<label>Material<select required value={l.serviceCode} onChange={e=>update(l.key,{serviceCode:e.target.value})}><option value="">Choose material</option>{rules.map(r=><option key={r.id} value={r.code}>{r.name}</option>)}</select></label>:l.type==='product'?<label>Product<select required value={l.productId} onChange={e=>update(l.key,{productId:e.target.value})}><option value="">Choose product</option>{products.filter(p=>p.status==='Active').map(p=><option value={p.id} key={p.id} disabled={!p.stock}>{p.name} · {money(Math.round(p.price*100))} · {p.stock} available</option>)}</select></label>:<label>Service / job name<input required minLength={2} value={l.name} onChange={e=>update(l.key,{name:e.target.value})}/></label>}
      <label>Quantity<input required type="number" min="1" max="100000" step="1" value={l.quantity} onChange={e=>update(l.key,{quantity:e.target.value})}/></label></div>
      {l.type==='large_format'&&<><div className="form-grid three"><label>Width<input required type="number" min="0.1" max="10000" step="0.01" value={l.width} onChange={e=>update(l.key,{width:e.target.value})}/></label><label>Height<input required type="number" min="0.1" max="10000" step="0.01" value={l.height} onChange={e=>update(l.key,{height:e.target.value})}/></label><label>Unit<select value={l.unit} onChange={e=>update(l.key,{unit:e.target.value as 'ft'|'in'})}><option value="ft">Feet</option><option value="in">Inches</option></select></label></div><div className="form-grid two"><label className="check-label"><input type="checkbox" checked={l.needsDesign} onChange={e=>update(l.key,{needsDesign:e.target.checked})}/>Needs design service</label>{l.needsDesign&&<label>Agreed design fee (GH₵)<input required type="number" min="100" step="0.01" value={l.designFee} onChange={e=>update(l.key,{designFee:e.target.value})}/></label>}</div></>}
      {l.type==='custom'&&<div className="form-grid two"><label>Agreed unit price (GH₵)<input type="number" min="0.01" step="0.01" value={l.unitPrice} onChange={e=>update(l.key,{unitPrice:e.target.value})}/><small>Leave blank to save for a manual quote.</small></label><label>Specifications<textarea value={l.description} onChange={e=>update(l.key,{description:e.target.value})} placeholder="Size, material, finish, colours and other instructions"/></label></div>}
      {l.type!=='product'&&<label>Artwork · optional<input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={e=>upload(l.key,e.target.files?.[0])}/>{l.artworkUrl&&<a href={l.artworkUrl} target="_blank" rel="noreferrer">{l.artworkName}</a>}<small>Artwork can also be supplied later.</small></label>}
    </article>)}<button className="button ghost" type="button" disabled={lines.length>=30} onClick={()=>setLines([...lines,line(rules)])}><Plus/>Add another item</button></section>
    <section className="surface counter-section"><h3><span>03</span> Fulfilment & notes</h3><div className="form-grid three"><label>Fulfilment<select value={form.fulfilmentMethod} onChange={e=>setForm({...form,fulfilmentMethod:e.target.value})}><option value="pickup">Pickup</option><option value="delivery">Delivery</option></select></label>{form.fulfilmentMethod==='delivery'&&<><label>Address<input required value={form.deliveryAddress} onChange={e=>setForm({...form,deliveryAddress:e.target.value})}/></label><label>Agreed delivery fee (GH₵)<input type="number" required min="0" step="0.01" value={form.deliveryFee} onChange={e=>setForm({...form,deliveryFee:e.target.value})}/></label></>}</div><label>Order notes<textarea value={form.customerNote} onChange={e=>setForm({...form,customerNote:e.target.value})}/></label></section></fieldset>
    <section className="counter-total surface"><div><span>{validEstimate?'Reviewed total':'Review before saving'}</span><strong>{validEstimate?money(estimate!.totalPesewas):'—'}</strong><small>{validEstimate&&estimate!.requiresReview?'Provisional · custom pricing needs confirmation before payment.':'Prices include the selected price book and rounding policy.'}</small></div><div className="action-row"><button className="button ghost" disabled={busy||uploading} type="submit">{busy?'Working…':'Review price'}</button>{validEstimate&&<button className="button primary" type="button" disabled={busy||uploading} onClick={create}>Create order</button>}</div></section>
  </form>;
}
function OrderDetail({id,onBack,onChanged}:{id:string;onBack:()=>void;onChanged:()=>void}){
  const [order,setOrder]=useState<Detail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState<'payment'|'refund'|null>(null),[amount,setAmount]=useState(''),[method,setMethod]=useState('cash'),[reference,setReference]=useState(''),[reason,setReason]=useState(''),[cancel,setCancel]=useState(false),[confirmed,setConfirmed]=useState(false),[date,setDate]=useState(new Date().toISOString().slice(0,16)),[requestKey,setRequestKey]=useState(key),[policy,setPolicy]=useState(''),[quotePrices,setQuotePrices]=useState<Record<string,string>>({});
  async function load(){try{setOrder(await api.orderDetail<Detail>(id));}catch(e){setError(errorText(e));}}
  useEffect(()=>{load();api.policies<{refundPolicy:string}>().then(p=>setPolicy(p.refundPolicy)).catch(e=>setError(errorText(e)));},[id]);
  async function run(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();setMode(null);await load();onChanged();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function record(e:React.FormEvent){e.preventDefault();const dto={requestKey,amountPesewas:Math.round(Number(amount)*100),method,externalReference:reference,occurredAt:new Date(date+'Z').toISOString()};await run(()=>mode==='refund'?api.recordRefund(id,{...dto,reason,cancelRemainingWork:cancel,confirmedExternalPayment:confirmed}):api.recordPayment(id,dto));}
  function open(m:'payment'|'refund'){setMode(m);setAmount('');setReference('');setReason('');setConfirmed(false);setCancel(false);setMethod('cash');setRequestKey(key());}
  if(!order)return <section className="surface counter-section"><button className="button ghost" onClick={onBack}>Back</button><p role="status">{error||'Loading order…'}</p></section>;
  return <div className="order-detail"><div className="section-title no-print"><button className="button ghost" onClick={onBack}><ArrowLeft/>Orders</button><button className="button ghost" onClick={()=>window.print()}><Printer/>Print receipt</button></div>{error&&<p role="alert" className="alert">{error}</p>}
    <section className="surface counter-section receipt"><span className="eyebrow">VIKIPAT / ORDER RECEIPT</span><h2>{order.orderNumber}</h2><p>{order.customerName} · {order.customerPhone||order.customerEmail}</p><p>{order.source.replace('_',' ')} · {order.status.replaceAll('_',' ')} · {order.paymentStatus.replaceAll('_',' ')}</p><div className="data-table"><table><thead><tr><th>Item</th><th>Qty</th><th>Total</th></tr></thead><tbody>{order.items.map(i=><tr key={i.id}><td>{i.name}<small>{(()=>{try{const s=JSON.parse(i.specification);return s.width?`${s.width} × ${s.height} ${s.unit}`:s.description||'';}catch{return '';}})()}</small></td><td>{i.quantity}</td><td>{money(i.totalPesewas)}</td></tr>)}</tbody></table></div><dl className="receipt-totals"><div><dt>Order total</dt><dd>{money(order.totalPesewas)}</dd></div><div><dt>Payments received</dt><dd>{money(order.collectedPesewas)}</dd></div><div><dt>Refunded</dt><dd>{money(order.refundedPesewas)}</dd></div><div><dt>Balance due</dt><dd>{money(order.outstandingPesewas)}</dd></div></dl>{order.customerNote&&<p className="receipt-note">{order.customerNote}</p>}<p className="muted">{order.customerEmail?'Track your order using the order number and email address.':'Keep this receipt and contact the shop with your order number for updates.'}</p></section>
    <section className="surface counter-section no-print"><h3>Next action</h3><div className="action-row">{!order.requiresReview&&order.status!=='cancelled'&&order.outstandingPesewas>0&&<button className="button primary" onClick={()=>open('payment')}>Record payment</button>}{order.refundablePesewas>0&&<button className="button ghost" onClick={()=>open('refund')}>Record external refund</button>}{!order.requiresReview&&!['cancelled','completed','on_hold'].includes(order.status)&&<button disabled={busy} className="button ghost" onClick={()=>run(()=>api.releaseOrder(id))}>Release to production</button>}</div><p className="muted">Counter orders can be released on agreed credit. Payment and production status are recorded separately. Returned stock must be inspected and adjusted in Inventory.</p>
    {order.requiresReview&&<form onSubmit={e=>{e.preventDefault();run(()=>api.confirmQuote(id,{items:order.items.filter(i=>i.kind==='custom'&&!i.unitPricePesewas).map(i=>({id:i.id,unitPricePesewas:Math.round(Number(quotePrices[i.id])*100)})),reason:'Agreed custom service quote'}));}}><h4>Confirm custom pricing</h4>{order.items.filter(i=>i.kind==='custom'&&!i.unitPricePesewas).map(i=><label key={i.id}>{i.name} · unit price (GH₵)<input required type="number" min="0.01" step="0.01" value={quotePrices[i.id]||''} onChange={e=>setQuotePrices({...quotePrices,[i.id]:e.target.value})}/></label>)}<button disabled={busy} className="button primary">Confirm quote</button></form>}
    {mode&&<form className="financial-entry" onSubmit={record}><h3>{mode==='refund'?'Record money already refunded':'Record payment already received'}</h3>{mode==='refund'&&<details><summary>Refund policy</summary><p>{policy}</p></details>}<div className="form-grid three"><label>Amount (GH₵)<input autoFocus required type="number" min="0.01" step="0.01" max={(mode==='refund'?order.refundablePesewas:order.outstandingPesewas)/100} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">Cash</option><option value="momo">Mobile money</option><option value="bank_transfer">Bank transfer</option>{mode==='refund'&&<option value="paystack">Paystack dashboard</option>}</select></label><label>Receipt / external reference<input required maxLength={150} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Cash receipt or transfer reference"/></label><label>Date & time (Accra)<input required type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label></div>{mode==='refund'&&<><label>Customer-visible reason<textarea required minLength={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="check-label"><input type="checkbox" checked={cancel} onChange={e=>setCancel(e.target.checked)}/>Cancel remaining production work</label><label className="check-label"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have already returned this money outside the app.</label></>}<div className="action-row"><button disabled={busy} className="button primary">{busy?'Saving…':'Save record'}</button><button type="button" className="button ghost" onClick={()=>setMode(null)}>Cancel</button></div></form>}
    </section><section className="surface counter-section"><h3>Payment & refund history</h3>{!order.payments.length&&!order.refunds.length&&<p className="muted">No payments recorded yet.</p>}{order.payments.map(p=><p key={p.id}>{p.provider} · {p.status} · {money(p.amountPesewas)} · {p.externalReference}</p>)}{order.refunds.map(r=><p key={r.id}>Refund · {money(r.amountPesewas)} · {r.method} · {r.externalReference}<br/><small>{r.reason}</small></p>)}</section>
  </div>;
}
export default function OrdersWorkspace({orders,products,rules,onChanged}:{orders:Order[];products:Product[];rules:PricingRule[];onChanged:()=>void}){
  const [creating,setCreating]=useState(false),[selected,setSelected]=useState(''),[search,setSearch]=useState('');
  if(selected)return <OrderDetail id={selected} onBack={()=>setSelected('')} onChanged={onChanged}/>;
  if(creating)return <CounterForm rules={rules} products={products} onCancel={()=>setCreating(false)} onCreated={id=>{setCreating(false);setSelected(id);onChanged();}}/>;
  const rows=orders.filter(o=>`${o.orderNumber} ${o.customerName} ${o.customerPhone} ${o.customerEmail}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="surface"><div className="section-title"><div><span className="eyebrow">ORDER DESK</span><h2>Every job, one place.</h2><p>Counter, online and salesperson orders.</p></div><button className="button primary" onClick={()=>setCreating(true)}><Plus/>New counter order</button></div><label className="order-search"><Search size={18}/><input placeholder="Search customer, phone or order number" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="data-table"><table><thead><tr><th>Order</th><th>Customer</th><th>Channel</th><th>Status</th><th>Order value</th><th/></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><strong>{o.orderNumber}</strong><small>{new Date(o.createdAt).toLocaleDateString('en-GB')}</small></td><td>{o.customerName}<small>{o.customerPhone||o.customerEmail}</small></td><td>{o.source.replace('_',' ')}</td><td>{o.paymentStatus.replaceAll('_',' ')}<small>{o.status.replaceAll('_',' ')}</small></td><td>{money(o.totalPesewas)}</td><td><button className="button ghost" onClick={()=>setSelected(o.id)}>Open</button></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No matching orders. Create a counter order to get started.</p>}</div></section>;
}
