import { OnApplicationBootstrap } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { Repository } from 'typeorm';
import { CreateGuestOrderDto, LargeFormatEstimateDto, UpdateProductionJobDto } from './dto';
import { Estimate, NotificationOutbox, Order, OrderItem, OrderStatus, OrderStatusHistory, OrderTrackingOtp, ProductionJob, ProductionJobActivity, ProductionStage, ServicePriceRule } from './entities';
import { NotificationService } from './notification.service';
import { PaymentService } from './payment.service';
import { type OrderSource, type PriceBookCode } from '@vikipat/domain';
export declare class OrderService implements OnApplicationBootstrap {
    private rules;
    private estimates;
    private orders;
    private items;
    private jobs;
    private jobActivity;
    private history;
    private otps;
    private outbox;
    private jwt;
    private notifications;
    private payments;
    constructor(rules: Repository<ServicePriceRule>, estimates: Repository<Estimate>, orders: Repository<Order>, items: Repository<OrderItem>, jobs: Repository<ProductionJob>, jobActivity: Repository<ProductionJobActivity>, history: Repository<OrderStatusHistory>, otps: Repository<OrderTrackingOtp>, outbox: Repository<NotificationOutbox>, jwt: JwtService, notifications: NotificationService, payments: PaymentService);
    onApplicationBootstrap(): Promise<void>;
    seed(): Promise<void>;
    listRules(): Promise<ServicePriceRule[]>;
    estimate(dto: LargeFormatEstimateDto, context?: {
        priceBook: PriceBookCode;
        allowConfirmedDesignFee: boolean;
    }): Promise<{
        name: string;
        areaSqFt: number;
        ratePesewas: number;
        roundingPolicy: import("@vikipat/pricing-engine").RoundingMode;
        designMessage: string | null;
        calculator: "large_format_area";
        disposition: import("@vikipat/domain").EstimateDisposition;
        serviceCode: string;
        serviceName: string;
        ruleVersion: number;
        width: number;
        height: number;
        unit: import("@vikipat/domain").DimensionUnit;
        quantity: number;
        areaPerPieceSqFt: number;
        totalAreaSqFt: number;
        priceBook: PriceBookCode;
        ratePesewasPerSqFt: number;
        basePesewas: number;
        designFeePesewas: number;
        totalPesewas: number;
        requiresReview: boolean;
        reviewReasons: string[];
        roundingMode: import("@vikipat/pricing-engine").RoundingMode;
        roundingStage: import("@vikipat/pricing-engine").RoundingStage;
        fingerprint: string;
    }>;
    createPublicEstimate(dto: LargeFormatEstimateDto): Promise<{
        estimateId: string;
        expiresAt: Date;
        name: string;
        areaSqFt: number;
        ratePesewas: number;
        roundingPolicy: import("@vikipat/pricing-engine").RoundingMode;
        designMessage: string | null;
        calculator: "large_format_area";
        disposition: import("@vikipat/domain").EstimateDisposition;
        serviceCode: string;
        serviceName: string;
        ruleVersion: number;
        width: number;
        height: number;
        unit: import("@vikipat/domain").DimensionUnit;
        quantity: number;
        areaPerPieceSqFt: number;
        totalAreaSqFt: number;
        priceBook: PriceBookCode;
        ratePesewasPerSqFt: number;
        basePesewas: number;
        designFeePesewas: number;
        totalPesewas: number;
        requiresReview: boolean;
        reviewReasons: string[];
        roundingMode: import("@vikipat/pricing-engine").RoundingMode;
        roundingStage: import("@vikipat/pricing-engine").RoundingStage;
        fingerprint: string;
    }>;
    createGuest(dto: CreateGuestOrderDto, source?: OrderSource): Promise<{
        success: boolean;
        orderNumber?: undefined;
        status?: undefined;
        paymentStatus?: undefined;
        totalPesewas?: undefined;
        requiresReview?: undefined;
        payment?: undefined;
    } | {
        orderNumber: string;
        status: string;
        paymentStatus: "paid" | "unpaid" | "pending" | "part_paid" | "refunded";
        totalPesewas: number;
        requiresReview: boolean;
        payment: {
            provider: string;
            reference: string;
            authorizationUrl: string;
            accessCode: string;
            providerConfigured: boolean;
        } | null;
        success?: undefined;
    }>;
    requestOtp(orderNumber: string, email: string): Promise<{
        devOtp?: string | undefined;
        message: string;
        expiresInSeconds: number;
    }>;
    verifyOtp(orderNumber: string, email: string, code: string): Promise<{
        token: string;
        order: {
            orderNumber: string;
            customerName: string;
            status: string;
            paymentStatus: "paid" | "unpaid" | "pending" | "part_paid" | "refunded";
            totalPesewas: number;
            promisedDate: string;
            createdAt: Date;
            updatedAt: Date;
            items: {
                name: string;
                quantity: number;
                totalPesewas: number;
                specification: any;
            }[];
            timeline: {
                status: string;
                note: string;
                createdAt: Date;
            }[];
        };
    }>;
    tracked(token: string | undefined): Promise<{
        orderNumber: string;
        customerName: string;
        status: string;
        paymentStatus: "paid" | "unpaid" | "pending" | "part_paid" | "refunded";
        totalPesewas: number;
        promisedDate: string;
        createdAt: Date;
        updatedAt: Date;
        items: {
            name: string;
            quantity: number;
            totalPesewas: number;
            specification: any;
        }[];
        timeline: {
            status: string;
            note: string;
            createdAt: Date;
        }[];
    }>;
    list(): Promise<Order[]>;
    listProductionJobs(role: string): Promise<{
        allowedStages: ProductionStage[];
        id: string;
        orderId: string;
        orderItemId: string;
        orderNumber: string;
        jobNumber: string;
        customerName: string;
        serviceCode: string;
        title: string;
        quantity: number;
        stage: ProductionStage;
        priority: "low" | "normal" | "rush";
        assignedTo: string;
        dueDate: string;
        specification: string;
        internalNote: string;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    listProductionIntake(): Promise<{
        id: string;
        orderNumber: string;
        customerName: string;
        source: import("./entities").OrderSource;
        paymentStatus: "paid" | "unpaid" | "pending" | "part_paid" | "refunded";
        status: OrderStatus;
        totalPesewas: number;
    }[]>;
    listProductionJobActivity(jobId: string): Promise<ProductionJobActivity[]>;
    addProductionJobNote(jobId: string, note: string, actor: string): Promise<ProductionJobActivity>;
    updateStatus(id: string, status: OrderStatus, note: string, customerVisible: boolean, actor: string): Promise<Order>;
    updateProductionJob(id: string, dto: UpdateProductionJobDto, actor: string, role: string): Promise<ProductionJob>;
    releaseOrderToProduction(orderId: string, actor?: string): Promise<ProductionJob[]>;
    private safeOrder;
    private hmac;
    private assertEstimateMatches;
    private checkoutNote;
    private orderStatusForStage;
    private uniqueNumber;
}
