import { FormEvent, useState } from 'react';
import { Check, ChevronRight, Clock3, KeyRound, Mail, PackageCheck, RotateCcw, ShieldCheck } from 'lucide-react';
import { Layout } from '../components/Layout';
import { useTitle } from '../lib/useReveal';
import { site } from '../site';

const API=(import.meta.env.VITE_API_URL||'http://localhost:3000/api').replace(/\/$/,'');
type OrderView={orderNumber:string;customerName:string;status:string;paymentStatus:string;totalPesewas:number;promisedDate:string;createdAt:string;updatedAt:string;items:{name:string;quantity:number;totalPesewas:number;specification:Record<string,unknown>}[];timeline:{status:string;note:string;createdAt:string}[]};
const money=(value:number)=>new Intl.NumberFormat('en-GH',{style:'currency',currency:'GHS'}).format(value/100);

export default function TrackOrder(){
  useTitle(`Track your order | ${site.fullName}`);
  const [step,setStep]=useState<'identify'|'verify'|'order'>('identify');
  const [orderNumber,setOrderNumber]=useState('');const [email,setEmail]=useState('');const [code,setCode]=useState('');
  const [order,setOrder]=useState<OrderView|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const request=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const response=await fetch(`${API}/order-tracking/request-otp`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderNumber:orderNumber.trim().toUpperCase(),email:email.trim().toLowerCase()})});const data=await response.json();if(!response.ok)throw new Error(data.message||'Could not send the verification code.');setNotice(data.devOtp?`Development code: ${data.devOtp}`:data.message);setStep('verify')}catch(e){setError(e instanceof Error?e.message:'Something went wrong.')}finally{setBusy(false)}};
  const verify=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const response=await fetch(`${API}/order-tracking/verify-otp`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderNumber:orderNumber.trim().toUpperCase(),email:email.trim().toLowerCase(),code})});const data=await response.json();if(!response.ok)throw new Error(data.message||'That code is invalid or has expired.');setOrder(data.order);setStep('order')}catch(e){setError(e instanceof Error?e.message:'Something went wrong.')}finally{setBusy(false)}};
  const reset=()=>{setStep('identify');setCode('');setError('');setNotice('');setOrder(null)};
  return <Layout><section className="tracking-shell">
    <div className="tracking-intro"><span className="tracking-mark"><PackageCheck aria-hidden="true"/></span><p className="tracking-kicker">Secure order tracking</p><h1>See exactly where your order is.</h1><p>No account required. We verify the email used for the order before showing any details.</p><div className="tracking-trust"><ShieldCheck aria-hidden="true"/><span>Your order information is protected by a one-time code.</span></div></div>
    <div className="tracking-panel" aria-live="polite">
      <div className="tracking-steps" aria-label="Tracking progress"><span className={step==='identify'?'is-current':'is-done'}>1</span><i/><span className={step==='verify'?'is-current':step==='order'?'is-done':''}>2</span><i/><span className={step==='order'?'is-current':''}>3</span></div>
      {step==='identify'&&<form className="tracking-form tracking-stage" onSubmit={request}><div><p className="tracking-overline">Find your order</p><h2>Enter your order details</h2><p>Use the order number and email address shown on your confirmation.</p></div><label>Order number<div className="tracking-input"><PackageCheck/><input value={orderNumber} onChange={e=>setOrderNumber(e.target.value.toUpperCase())} placeholder="VP-AB12CD34" pattern="VP-[A-Z0-9]{8}" required autoComplete="off"/></div></label><label>Email address<div className="tracking-input"><Mail/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required autoComplete="email"/></div></label>{error&&<p className="tracking-error" role="alert">{error}</p>}<button className="tracking-submit" disabled={busy}>{busy?'Sending code…':<>Send verification code <ChevronRight/></>}</button></form>}
      {step==='verify'&&<form className="tracking-form tracking-stage" onSubmit={verify}><div className="tracking-code-icon"><KeyRound/></div><div><p className="tracking-overline">Email verification</p><h2>Enter the six-digit code</h2><p>We sent a code to <strong>{email}</strong>. It expires in 10 minutes.</p></div>{notice&&<p className="tracking-notice">{notice}</p>}<label>Verification code<input className="otp-input" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000" required autoFocus/></label>{error&&<p className="tracking-error" role="alert">{error}</p>}<button className="tracking-submit" disabled={busy||code.length!==6}>{busy?'Verifying…':<>Verify and view order <ChevronRight/></>}</button><button className="tracking-link" type="button" onClick={reset}><RotateCcw/> Use different details</button></form>}
      {step==='order'&&order&&<div className="tracking-stage order-view"><div className="order-view-head"><div><p className="tracking-overline">{order.orderNumber}</p><h2>{order.status}</h2><p>Hi {order.customerName}, here is the latest progress on your order.</p></div><span className="order-status"><Check/> Verified</span></div><dl className="order-facts"><div><dt>Order total</dt><dd>{money(order.totalPesewas)}</dd></div><div><dt>Payment</dt><dd>{order.paymentStatus.replace('_',' ')}</dd></div><div><dt>Placed</dt><dd>{new Date(order.createdAt).toLocaleDateString('en-GH',{day:'numeric',month:'short',year:'numeric'})}</dd></div></dl><div className="order-items"><h3>Order details</h3>{order.items.map((item,index)=><div className="order-item" key={`${item.name}-${index}`}><div><strong>{item.name}</strong><span>Quantity {item.quantity}</span></div><strong>{money(item.totalPesewas)}</strong></div>)}</div><div className="order-timeline"><h3>Progress</h3>{order.timeline.map((event,index)=><div className="timeline-event" key={`${event.createdAt}-${index}`}><span><Check/></span><div><strong>{event.status}</strong>{event.note&&<p>{event.note}</p>}<time><Clock3/> {new Date(event.createdAt).toLocaleString('en-GH',{dateStyle:'medium',timeStyle:'short'})}</time></div></div>)}</div><button className="tracking-link" type="button" onClick={reset}><RotateCcw/> Track another order</button></div>}
    </div>
  </section></Layout>
}
