import { BadRequestException, Injectable } from '@nestjs/common';
import { DataSource } from 'typeorm';
import { Cron } from '@nestjs/schedule';
import { AttendanceRecord, Customer, Employee, NotificationOutbox, Order, OrderItem, OrderRefund, PaymentTransaction, PayrollRun, Product, ProductionJob, ProductionJobActivity, QuoteRequest, ServicePriceRule, BusinessPolicy } from './entities';
import { balances, dateOnly, successfulPayment } from './finance';
import { CommerceService } from './commerce.service';
const DAY=86400000;
const day=(d:Date)=>d.toISOString().slice(0,10);
const sum=<T>(rows:T[],fn:(r:T)=>number)=>rows.reduce((s,r)=>s+fn(r),0);
const change=(a:number,b:number)=>b?Math.round((a-b)/Math.abs(b)*1000)/10:null;
export interface Insight {id:string;severity:'critical'|'warning'|'opportunity'|'good';title:string;detail:string;action:string;view?:string;metric?:string;evidence?:{id:string;label:string}[];}
@Injectable()
export class AnalyticsService {
  constructor(private db:DataSource,private commerce:CommerceService){}
  async overview(days=30,from?:string,to?:string){
    if(!Number.isInteger(days)||days<1||days>365)throw new BadRequestException('Choose between 1 and 365 days');
    let end:Date,start:Date;
    try{end=to?new Date(dateOnly(to)+'T00:00:00Z'):new Date(day(new Date())+'T00:00:00Z');end=new Date(end.getTime()+DAY);start=from?new Date(dateOnly(from)+'T00:00:00Z'):new Date(end.getTime()-days*DAY);}catch{throw new BadRequestException('Enter valid report dates');}
    const duration=end.getTime()-start.getTime();days=Math.round(duration/DAY);
    if(days<1||days>366)throw new BadRequestException('Report range must be 1–366 days');
    const prior=new Date(start.getTime()-duration), within=(date:Date,a=start,b=end)=>date>=a&&date<b;
    const [orders,items,payments,refunds,jobs,activity,quotes,products,customers,runs,notifications,rules]=await Promise.all([this.db.getRepository(Order).find(),this.db.getRepository(OrderItem).find(),this.db.getRepository(PaymentTransaction).find(),this.db.getRepository(OrderRefund).find(),this.db.getRepository(ProductionJob).find(),this.db.getRepository(ProductionJobActivity).find(),this.db.getRepository(QuoteRequest).find(),this.db.getRepository(Product).find(),this.db.getRepository(Customer).find(),this.db.getRepository(PayrollRun).find(),this.db.getRepository(NotificationOutbox).find(),this.db.getRepository(ServicePriceRule).find()]);
    const paid=payments.filter(successfulPayment), paymentDate=(p:PaymentTransaction)=>p.paidAt||p.updatedAt;
    const receipts=paid.filter(p=>within(paymentDate(p))), returns=refunds.filter(r=>within(r.occurredAt));
    const net=sum(receipts,p=>p.amountPesewas)-sum(returns,r=>r.amountPesewas);
    const previousNet=sum(paid.filter(p=>within(paymentDate(p),prior,start)),p=>p.amountPesewas)-sum(refunds.filter(r=>within(r.occurredAt,prior,start)),r=>r.amountPesewas);
    const current=orders.filter(o=>within(o.createdAt)), previous=orders.filter(o=>within(o.createdAt,prior,start));
    const orderMap=new Map(orders.map(o=>[o.id,o]));
    const moneyByOrder=new Map<string,number>();for(const p of receipts)moneyByOrder.set(p.orderId,(moneyByOrder.get(p.orderId)||0)+p.amountPesewas);for(const r of returns)moneyByOrder.set(r.orderId,(moneyByOrder.get(r.orderId)||0)-r.amountPesewas);
    const live=jobs.filter(j=>!['fulfilled','cancelled'].includes(j.stage));
    const receivables=orders.filter(o=>o.status!=='cancelled'&&!o.requiresReview).map(o=>({...o,...balances(o,payments)})).filter(o=>o.outstandingPesewas>0);
    const allCustomerValues=customers.map(c=>{const mine=orders.filter(o=>o.customerId===c.id);return {...c,lifetimeValuePesewas:sum(mine,o=>balances(o,payments).netCollectedPesewas),orderCount:mine.length};});
    const materialMap=new Map<string,{code:string;name:string;revenuePesewas:number;jobs:number;areaSqFt:number}>();
    // Allocate each order's net cash to lines, with the rounding remainder assigned
    // to the last component so line allocations plus delivery equal net cash exactly.
    for(const [id,amount] of moneyByOrder){const order=orderMap.get(id);if(!order||!order.totalPesewas)continue;const lines=items.filter(i=>i.orderId===id);const components=[...lines.map(i=>({key:i.serviceCode||i.productId,name:i.name,weight:i.totalPesewas,item:i})),{key:'delivery',name:'Delivery',weight:order.deliveryFeePesewas||0,item:null}].filter(c=>c.weight>0);let allocated=0;components.forEach((c,index)=>{const share=index===components.length-1?amount-allocated:Math.round(amount*c.weight/order.totalPesewas);allocated+=share;const row=materialMap.get(c.key)||{code:c.key,name:c.name,revenuePesewas:0,jobs:0,areaSqFt:0};row.revenuePesewas+=share;row.jobs+=c.item?1:0;try{row.areaSqFt+=Number(JSON.parse(c.item?.specification||'{}').totalAreaSqFt||0);}catch{}materialMap.set(c.key,row);});}
    const byDay=Array.from({length:days},(_,i)=>({date:day(new Date(start.getTime()+i*DAY)),revenuePesewas:0,orders:0}));const daily=new Map(byDay.map(d=>[d.date,d]));
    for(const p of receipts){const d=daily.get(day(paymentDate(p)));if(d)d.revenuePesewas+=p.amountPesewas;}for(const r of returns){const d=daily.get(day(r.occurredAt));if(d)d.revenuePesewas-=r.amountPesewas;}for(const o of current){const d=daily.get(day(o.createdAt));if(d)d.orders++;}
    const finished=jobs.map(j=>({job:j,event:activity.filter(a=>a.jobId===j.id&&a.toStage==='fulfilled').sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime())[0]})).filter(x=>x.event&&within(x.event.createdAt));
    const dueFinished=finished.filter(x=>x.job.dueDate), onTime=dueFinished.filter(x=>day(x.event.createdAt)<=x.job.dueDate).length;
    const paidCurrent=current.filter(o=>balances(o,payments).collectedPesewas>=o.totalPesewas&&o.totalPesewas>0);
    const quoteWindow=quotes.filter(q=>within(q.createdAt));
    const repeat=allCustomerValues.filter(c=>c.orderCount>1);
    const productDemand=products.map(p=>{const sold=items.filter(i=>i.productId===p.id&&current.some(o=>o.id===i.orderId&&balances(o,payments).collectedPesewas>0));const units=sum(sold,i=>i.quantity);return {id:p.id,name:p.name,stock:p.stock,units,daysOfStock:units?Math.round(p.stock/(units/days)*10)/10:null};});
    const insights:Insight[]=[];
    const add=(id:string,severity:Insight['severity'],title:string,detail:string,action:string,view:string,evidence:{id:string;label:string}[]=[])=>insights.push({id,severity,title,detail,action,view,evidence:evidence.slice(0,20)});
    const overdue=live.filter(j=>j.dueDate&&j.dueDate<day(new Date()));if(overdue.length)add('overdue','critical',`${overdue.length} jobs are overdue`,'Open jobs with a due date before today.','Review the jobs and agree revised dates with customers.','operations',overdue.map(j=>({id:j.id,label:j.jobNumber})));
    const stale=receivables.filter(o=>Date.now()-o.createdAt.getTime()>2*DAY);if(stale.length)add('balances','warning',`${stale.length} orders have balances older than 48 hours`,`GHS ${(sum(stale,o=>o.outstandingPesewas)/100).toFixed(2)} remains uncollected; age is measured from order creation.`, 'Review agreed payment terms before following up.','orders',stale.map(o=>({id:o.id,label:o.orderNumber})));
    const blocked=live.filter(j=>j.stage==='blocked');if(blocked.length)add('blocked','warning',`${blocked.length} jobs are blocked`,'The production records explicitly mark these jobs blocked.','Review job notes and assign the next action.','operations',blocked.map(j=>({id:j.id,label:j.jobNumber})));
    const failed=notifications.filter(n=>n.status==='failed');if(failed.length)add('email','warning',`${failed.length} notifications failed`,'Delivery errors are recorded in the notification log.','Correct the recipient or provider issue, then retry.','communications',failed.map(n=>({id:n.id,label:n.recipient})));
    const low=productDemand.filter(p=>p.stock===0||(p.daysOfStock!==null&&p.daysOfStock<=7));if(low.length)add('stock','warning',`${low.length} products need a stock review`,'Coverage uses paid-order units in this period. It is an estimate, not a demand forecast.','Review stock and supplier lead times.','inventory',low.map(p=>({id:p.id,label:p.name})));
    const cold=quotes.filter(q=>q.status==='New'&&Date.now()-q.createdAt.getTime()>2*DAY);if(cold.length)add('quotes','opportunity',`${cold.length} new quotes are over 48 hours old`,'These requests are still marked New; unlogged phone conversations are not visible here.','Review and respond to open requests.','quotes',cold.map(q=>({id:q.id,label:q.name})));
    const soldCodes=new Set(items.filter(i=>current.some(o=>o.id===i.orderId&&balances(o,payments).collectedPesewas>0)).map(i=>i.serviceCode));const quiet=rules.filter(r=>r.active&&!soldCodes.has(r.code));if(current.length>=10&&quiet.length)add('quiet-services','opportunity',`${quiet.length} active services have no paid orders in this period`,'Checked all order lines, not only the top-ranked materials.','Review demand and catalogue visibility before changing stock.','pricing',quiet.map(r=>({id:r.id,label:r.name})));
    if(previousNet>0&&net<previousNet*.8)add('collections-down','warning','Net collections fell by more than 20%',`GHS ${(net/100).toFixed(2)} versus GHS ${(previousNet/100).toFixed(2)} in the preceding ${days} days.`,'Compare channels, refunds and outstanding balances; the cause is not established.','analytics');
    const missing=orders.filter(o=>['paid','part_paid','part_refunded','refunded'].includes(o.paymentStatus)&&!paid.some(p=>p.orderId===o.id));if(missing.length)add('missing-receipts','critical',`${missing.length} orders have no supporting payment record`,'A paid/refunded status exists without a recorded receipt. These amounts are excluded from collections.','Reconcile the original receipts before relying on historical reports.','finance',missing.map(o=>({id:o.id,label:o.orderNumber})));
    const stageDurations=['intake','artwork_review','proofing','production_ready','in_production','quality_check','ready','blocked'].map(stage=>{const stageJobs=live.filter(j=>j.stage===stage);return {stage,count:stageJobs.length,oldestHours:stageJobs.length?Math.round(Math.max(...stageJobs.map(j=>{const moved=activity.filter(a=>a.jobId===j.id&&a.toStage===stage).sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime())[0];return (Date.now()-(moved?.createdAt||j.createdAt).getTime())/3600000;}))):0};});
    const bySource=['online','walk_in','salesperson'].map(source=>{const rows=current.filter(o=>o.source===source);const cash=sum([...moneyByOrder],([id,value])=>orderMap.get(id)?.source===source?value:0);return {source,orders:rows.length,revenuePesewas:cash,averagePesewas:rows.length?Math.round(sum(rows,o=>o.totalPesewas)/rows.length):0};});
    return {generatedAt:new Date().toISOString(),windowDays:days,from:day(start),to:day(new Date(end.getTime()-DAY)),basis:'Collections by receipt date; refunds by refund date. Order counts/value by order date. Customer lifetime and open workload are all-time. Currency GHS; timezone Africa/Accra.',limitations:['Profit/margin unavailable: direct costs are not recorded.','Website visitor conversion unavailable: visitor events are not collected.','Historical migrated payment dates use the last transaction update when the original date was unavailable.','Inventory coverage uses paid-order demand, not audited consumption.'],
      revenue:{netPesewas:net,collectedPesewas:sum(receipts,p=>p.amountPesewas),priorNetPesewas:previousNet,changePercent:change(net,previousNet),refundedPesewas:sum(returns,r=>r.amountPesewas),averageOrderPesewas:current.length?Math.round(sum(current,o=>o.totalPesewas)/current.length):0,orderValuePesewas:sum(current,o=>o.totalPesewas),outstandingPesewas:sum(receivables,o=>o.outstandingPesewas)},
      orders:{total:current.length,priorTotal:previous.length,changePercent:change(current.length,previous.length),paid:paidCurrent.length,awaitingPayment:current.length-paidCurrent.length,conversionPercent:current.length?Math.round(paidCurrent.length/current.length*1000)/10:0},
      customers:{total:customers.length,repeat:repeat.length,repeatRatePercent:customers.length?Math.round(repeat.length/customers.length*1000)/10:0,newInWindow:customers.filter(c=>c.firstOrderAt&&within(c.firstOrderAt)).length,averageLifetimePesewas:customers.length?Math.round(sum(allCustomerValues,c=>c.lifetimeValuePesewas)/customers.length):0},
      production:{openJobs:live.length,blocked:blocked.length,overdue:overdue.length,unassigned:live.filter(j=>!j.assignedTo).length,completed:finished.length,onTimePercent:dueFinished.length?Math.round(onTime/dueFinished.length*100):null,averageCycleHours:finished.length?Math.round(sum(finished,x=>(x.event.createdAt.getTime()-x.job.createdAt.getTime())/3600000)/finished.length):null,stages:stageDurations},
      quotes:{open:quotes.filter(q=>['New','Contacted','Quoted'].includes(q.status)).length,won:quoteWindow.filter(q=>q.status==='Won').length,winRatePercent:quoteWindow.length?Math.round(quoteWindow.filter(q=>q.status==='Won').length/quoteWindow.length*1000)/10:0},inventory:{outOfStock:products.filter(p=>p.status==='Active'&&p.stock===0).length,lowStock:products.filter(p=>p.status==='Active'&&p.stock>0&&p.stock<=5).length,coverage:productDemand},
      payroll:{paidPesewas:sum(runs.filter(r=>r.status==='paid'&&r.paidAt&&within(r.paidAt)),r=>r.netPesewas),awaitingPaymentPesewas:sum(runs.filter(r=>r.status==='approved'),r=>r.netPesewas)},
      receivables:receivables.map(o=>({id:o.id,orderNumber:o.orderNumber,customerName:o.customerName,ageDays:Math.floor((Date.now()-o.createdAt.getTime())/DAY),outstandingPesewas:o.outstandingPesewas})),
      revenueByDay:byDay,topMaterials:[...materialMap.values()].sort((a,b)=>b.revenuePesewas-a.revenuePesewas),bySource,topCustomers:allCustomerValues.sort((a,b)=>b.lifetimeValuePesewas-a.lifetimeValuePesewas).slice(0,10),insights:insights.sort((a,b)=>({critical:0,warning:1,opportunity:2,good:3}[a.severity]-{critical:0,warning:1,opportunity:2,good:3}[b.severity]))};
  }
  async insights(){return (await this.overview()).insights;}
  async emailReport(actor:string){const settings=await this.commerce.policies();if(!settings.reportEmail)throw new BadRequestException('Set a report recipient in policies first');const report=await this.overview();await this.db.getRepository(NotificationOutbox).save({orderId:'',channel:'email',recipient:settings.reportEmail,template:'management_report',payload:JSON.stringify({subject:`Vikipat management report · ${report.to}`,text:`${report.from} to ${report.to}\n\nNet collections: GHS ${(report.revenue.netPesewas/100).toFixed(2)}\nRefunds: GHS ${(report.revenue.refundedPesewas/100).toFixed(2)}\nOutstanding: GHS ${(report.revenue.outstandingPesewas/100).toFixed(2)}\nOrders: ${report.orders.total}\n\n${report.insights.map(i=>`${i.title}\n${i.detail}\n${i.action}`).join('\n\n')}\n\n${report.basis}`})});return {queued:true};}
  @Cron('0 8 * * *',{timeZone:'Africa/Accra'})
  async scheduledReport(){const p=await this.commerce.policies();if(p.reportSchedule==='off'||!p.reportEmail||(p.reportSchedule==='weekly'&&new Date().getUTCDay()!==1))return;const key=`report-${day(new Date())}`;await this.db.transaction(async m=>{if(m.connection.options.type==='postgres')await m.query('SELECT pg_advisory_xact_lock(hashtext($1))',[key]);if(await m.getRepository(BusinessPolicy).findOneBy({id:key}))return;await this.emailReport('scheduler');await m.getRepository(BusinessPolicy).save({id:key,value:'queued'});});}
}
