import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Between, DataSource, EntityManager, IsNull } from 'typeorm';
import { randomUUID } from 'crypto';
import { AttendanceRecord, AuditLog, Employee, NotificationOutbox, PayrollRun, Payslip, ProductionJobActivity } from './entities';
import { ClockInDto, CreateEmployeeDto, RecordAttendanceDto, UpdateEmployeeDto, CreatePayrollRunDto, UpdatePayslipDto } from './people.dto';
import { CommerceService, DEFAULT_POLICIES } from './commerce.service';
import { dateOnly } from './finance';
import { lockedFindOne } from './db';
const today=()=>new Date().toISOString().slice(0,10);
export function computePay(employee:Employee, days:number, minutes:number, overtimeMinutes:number, policy:typeof DEFAULT_POLICIES, start:string, end:string){
  const hourly=employee.payType==='hourly'?employee.payRatePesewas:employee.payRatePesewas/(policy.shiftMinutes/60)/(employee.payType==='monthly'?policy.workingDaysPerMonth:1);
  let base=0;
  if(employee.payType==='monthly'){
    // Prorate each calendar month separately, including hire date, so a short
    // run cannot accidentally pay a whole monthly salary.
    const begin=new Date(start>employee.hiredOn?start:employee.hiredOn||start), stop=new Date(end);
    for(let d=new Date(begin);d<=stop;d.setUTCDate(d.getUTCDate()+1)){const daysInMonth=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();base+=employee.payRatePesewas/daysInMonth;}
  }else base=employee.payType==='daily'?employee.payRatePesewas*days:minutes/60*hourly;
  const overtime=overtimeMinutes/60*hourly*(employee.payType==='hourly'?policy.overtimeMultiplier-1:policy.overtimeMultiplier);
  return {basePesewas:Math.round(base),overtimePesewas:Math.round(overtime)};
}
@Injectable()
export class PeopleService {
  constructor(private db:DataSource,private commerce:CommerceService){}
  private audit(m:EntityManager,actor:string,action:string,entity:string,id:string,details:unknown={}){return m.getRepository(AuditLog).save({actorEmail:actor,action,entity,entityId:id,details:JSON.stringify(details)});}
  private async lock(m:EntityManager){if(m.connection.options.type==='postgres')await m.query("SELECT pg_advisory_xact_lock(hashtext('vikipat-people-payroll'))");}
  private validDate(value:string){try{return dateOnly(value);}catch{throw new BadRequestException('Enter a valid calendar date');}}
  private range(from?:string,to?:string){const start=this.validDate(from||new Date(Date.now()-30*86400000).toISOString().slice(0,10)),end=this.validDate(to||today());if(end<start)throw new BadRequestException('End date cannot precede start');return {start,end};}
  async listEmployees(includeInactive=false){const [employees,open]=await Promise.all([this.db.getRepository(Employee).find({order:{fullName:'ASC'}}),this.db.getRepository(AttendanceRecord).findBy({clockOut:IsNull()})]);return employees.filter(e=>includeInactive||e.employmentStatus!=='terminated').map(e=>({...e,onShift:open.some(r=>r.employeeId===e.id)}));}
  private async checkEmail(m:EntityManager,email?:string,id?:string){if(!email)return;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new BadRequestException('Enter a valid employee email');const existing=await m.getRepository(Employee).findOneBy({email:email.trim().toLowerCase()});if(existing&&existing.id!==id)throw new ConflictException('Employee email is already in use');}
  async createEmployee(dto:CreateEmployeeDto,actor:string){return this.db.transaction(async m=>{await this.lock(m);await this.checkEmail(m,dto.email);if(dto.hiredOn)this.validDate(dto.hiredOn);const repo=m.getRepository(Employee);const e=await repo.save(repo.create({...dto,email:dto.email?.trim().toLowerCase()||'',staffNumber:dto.staffNumber?.trim()||`VP-${randomUUID().slice(0,8).toUpperCase()}`,hiredOn:dto.hiredOn||today()}));await this.audit(m,actor,'employee_created','employee',e.id);return e;});}
  async updateEmployee(id:string,dto:UpdateEmployeeDto,actor:string){return this.db.transaction(async m=>{await this.lock(m);const e=await lockedFindOne(m,Employee,{id});if(!e)throw new NotFoundException('Employee not found');await this.checkEmail(m,dto.email,id);Object.assign(e,dto);if(dto.email!==undefined)e.email=dto.email.trim().toLowerCase();await m.getRepository(Employee).save(e);await this.audit(m,actor,'employee_updated','employee',id,dto);return e;});}
  private async assertEditable(m:EntityManager,date:string){const runs=await m.getRepository(PayrollRun).find();if(runs.some(r=>r.status!=='cancelled'&&date>=r.periodStart&&date<=r.periodEnd))throw new ConflictException('Attendance is included in a pay run. Cancel the draft/approved run before correcting it; paid periods are locked.');}
  async clockIn(dto:ClockInDto,actor:string){const p=await this.commerce.policies();return this.db.transaction(async m=>{await this.lock(m);const employee=await m.getRepository(Employee).findOneBy({id:dto.employeeId});if(!employee||employee.employmentStatus!=='active')throw new BadRequestException('Choose an active employee');await this.assertEditable(m,today());if(await m.getRepository(AttendanceRecord).findOneBy({employeeId:employee.id,clockOut:IsNull()}))throw new ConflictException('Employee is already clocked in');const now=new Date();const r=await m.getRepository(AttendanceRecord).save({employeeId:employee.id,employeeName:employee.fullName,workDate:today(),clockIn:now,clockOut:null,status:now.getUTCHours()*60+now.getUTCMinutes()>p.shiftStartHour*60+p.lateGraceMinutes?'late':'present',note:dto.note||'',recordedBy:actor});await this.audit(m,actor,'clock_in','attendance',r.id);return r;});}
  async clockOut(employeeId:string,actor:string){const p=await this.commerce.policies();return this.db.transaction(async m=>{await this.lock(m);const r=await m.getRepository(AttendanceRecord).findOneBy({employeeId,clockOut:IsNull()});if(!r)throw new NotFoundException('No open shift');await this.assertEditable(m,r.workDate);r.clockOut=new Date();r.minutesWorked=Math.round((r.clockOut.getTime()-r.clockIn.getTime())/60000);if(r.minutesWorked>1440)throw new BadRequestException('Shift exceeds 24 hours. Correct attendance with the actual clock-out time.');r.overtimeMinutes=Math.max(0,r.minutesWorked-p.shiftMinutes);await m.getRepository(AttendanceRecord).save(r);await this.audit(m,actor,'clock_out','attendance',r.id);return r;});}
  async recordAttendance(dto:RecordAttendanceDto,actor:string,id?:string){const p=await this.commerce.policies();return this.db.transaction(async m=>{await this.lock(m);const employee=await m.getRepository(Employee).findOneBy({id:dto.employeeId});if(!employee)throw new NotFoundException('Employee not found');const clockIn=new Date(dto.clockIn),worked=['present','late'].includes(dto.status),clockOut=dto.clockOut?new Date(dto.clockOut):worked?null:clockIn;
    if(!Number.isFinite(clockIn.getTime())||(clockOut&&!Number.isFinite(clockOut.getTime())))throw new BadRequestException('Enter valid shift times');
    const workDate=this.validDate(dto.workDate||clockIn.toISOString().slice(0,10));if(workDate!==clockIn.toISOString().slice(0,10))throw new BadRequestException('Work date must match the shift start date');await this.assertEditable(m,workDate);
    const minutes=clockOut?Math.round((clockOut.getTime()-clockIn.getTime())/60000):0;if(minutes<0||minutes>1440)throw new BadRequestException('Shift must be between 0 and 24 hours');
    const repo=m.getRepository(AttendanceRecord),existing=id?await repo.findOneBy({id}):null;if(id&&!existing)throw new NotFoundException('Attendance record not found');if(existing)await this.assertEditable(m,existing.workDate);
    const records=await repo.findBy({employeeId:dto.employeeId});if(records.some(r=>r.id!==id&&(r.clockOut?.getTime()??Infinity)>clockIn.getTime()&&r.clockIn.getTime()<(clockOut?.getTime()??Infinity)))throw new ConflictException('This overlaps an existing attendance record');
    const row=await repo.save(repo.create({...existing,employeeId:employee.id,employeeName:employee.fullName,workDate,clockIn,clockOut,status:dto.status,minutesWorked:worked?minutes:0,overtimeMinutes:worked?Math.max(0,minutes-p.shiftMinutes):0,note:dto.note||'',recordedBy:actor}));await this.audit(m,actor,id?'attendance_corrected':'attendance_recorded','attendance',row.id,{before:existing,after:row});return row;});}
  async listAttendance(from?:string,to?:string,employeeId?:string){const {start,end}=this.range(from,to);return this.db.getRepository(AttendanceRecord).find({where:{workDate:Between(start,end),...(employeeId?{employeeId}:{})},order:{workDate:'DESC',clockIn:'DESC'}});}
  async createPayrollRun(dto:CreatePayrollRunDto,actor:string){const {start,end}=this.range(dto.periodStart,dto.periodEnd),policy=await this.commerce.policies();if(new Date(end).getTime()-new Date(start).getTime()>366*86400000)throw new BadRequestException('Pay period cannot exceed one year');return this.db.transaction(async m=>{await this.lock(m);const repo=m.getRepository(PayrollRun);const all=await repo.find();if(all.some(r=>r.status!=='cancelled'&&r.periodStart<=end&&r.periodEnd>=start))throw new ConflictException('Pay period overlaps an existing run');const staff=(await m.getRepository(Employee).find()).filter(e=>e.employmentStatus==='active'&&e.hiredOn<=end);if(!staff.length)throw new BadRequestException('No active employees in this period');if(staff.some(e=>!e.payRatePesewas))throw new BadRequestException('Set a positive pay rate for every active employee first');const records=await m.getRepository(AttendanceRecord).findBy({workDate:Between(start,end)});if(records.some(r=>!r.clockOut&&staff.some(e=>e.id===r.employeeId)))throw new BadRequestException('Close or correct open shifts before preparing payroll');
      const run=await repo.save(repo.create({reference:`PAY-${start}-${randomUUID().slice(0,6).toUpperCase()}`,periodStart:start,periodEnd:end,status:'draft',preparedBy:actor,note:dto.note||'',policySnapshot:JSON.stringify(policy)}));let gross=0;
      for(const e of staff){const mine=records.filter(r=>r.employeeId===e.id&&r.workDate>=e.hiredOn&&['present','late'].includes(r.status));const daily=new Map<string,number>();for(const r of mine)daily.set(r.workDate,(daily.get(r.workDate)||0)+r.minutesWorked);const minutes=[...daily.values()].reduce((a,b)=>a+b,0),overtime=[...daily.values()].reduce((a,b)=>a+Math.max(0,b-policy.shiftMinutes),0);const pay=computePay(e,daily.size,minutes,overtime,policy,start,end);const total=pay.basePesewas+pay.overtimePesewas;if(!Number.isSafeInteger(total)||total>100000000)throw new BadRequestException('Calculated pay exceeds supported amount');await m.getRepository(Payslip).save({payrollRunId:run.id,employeeId:e.id,employeeName:e.fullName,staffNumber:e.staffNumber,payType:e.payType,payRatePesewas:e.payRatePesewas,daysWorked:daily.size,minutesWorked:minutes,overtimeMinutes:overtime,...pay,grossPesewas:total,netPesewas:total});gross+=total;}
      run.grossPesewas=gross;run.netPesewas=gross;run.payslipCount=staff.length;await repo.save(run);await this.audit(m,actor,'payroll_prepared','payroll_run',run.id,{policy,periodStart:start,periodEnd:end});return run;});}
  listPayrollRuns(){return this.db.getRepository(PayrollRun).find({order:{periodStart:'DESC'}});}
  async payrollRun(id:string){const run=await this.db.getRepository(PayrollRun).findOneBy({id});if(!run)throw new NotFoundException('Pay run not found');return {...run,payslips:await this.db.getRepository(Payslip).find({where:{payrollRunId:id},order:{employeeName:'ASC'}})};}
  async updatePayslip(id:string,dto:UpdatePayslipDto,actor:string){return this.db.transaction(async m=>{await this.lock(m);const slip=await m.getRepository(Payslip).findOneBy({id});if(!slip)throw new NotFoundException('Payslip not found');const run=await lockedFindOne(m,PayrollRun,{id:slip.payrollRunId});if(!run||run.status!=='draft')throw new BadRequestException('Only draft payslips can change');Object.assign(slip,dto);slip.grossPesewas=slip.basePesewas+slip.overtimePesewas+slip.bonusPesewas;if(slip.deductionsPesewas>slip.grossPesewas)throw new BadRequestException('Deductions cannot exceed gross pay');slip.netPesewas=slip.grossPesewas-slip.deductionsPesewas;await m.getRepository(Payslip).save(slip);const slips=await m.getRepository(Payslip).findBy({payrollRunId:run.id});run.grossPesewas=slips.reduce((s,p)=>s+p.grossPesewas,0);run.deductionsPesewas=slips.reduce((s,p)=>s+p.deductionsPesewas,0);run.netPesewas=slips.reduce((s,p)=>s+p.netPesewas,0);await m.getRepository(PayrollRun).save(run);await this.audit(m,actor,'payslip_updated','payslip',id,dto);return slip;});}
  async updatePayrollStatus(id:string,status:'approved'|'paid'|'cancelled',actor:string){return this.db.transaction(async m=>{await this.lock(m);const run=await lockedFindOne(m,PayrollRun,{id});if(!run)throw new NotFoundException('Pay run not found');if(!({draft:['approved','cancelled'],approved:['paid','cancelled'],paid:[],cancelled:[]} as Record<string,string[]>)[run.status].includes(status))throw new BadRequestException(`Cannot move ${run.status} payroll to ${status}`);run.status=status;if(status==='approved')run.approvedBy=actor;if(status==='paid')run.paidAt=new Date();await m.getRepository(PayrollRun).save(run);await this.audit(m,actor,`payroll_${status}`,'payroll_run',id,{amount:run.netPesewas});return run;});}
  async emailPayslip(id:string,actor:string){const slip=await this.db.getRepository(Payslip).findOneBy({id});if(!slip)throw new NotFoundException('Payslip not found');const [run,e]=await Promise.all([this.db.getRepository(PayrollRun).findOneBy({id:slip.payrollRunId}),this.db.getRepository(Employee).findOneBy({id:slip.employeeId})]);if(!run||!['approved','paid'].includes(run.status))throw new BadRequestException('Approve the run before emailing payslips');if(!e?.email)throw new BadRequestException('Set an employee email first');return this.db.transaction(async m=>{const row=await m.getRepository(NotificationOutbox).save({orderId:'',channel:'email',recipient:e.email,template:'payslip',payload:JSON.stringify({subject:`Payslip · ${run.reference}`,text:`${slip.employeeName} (${slip.staffNumber})\n${run.periodStart} to ${run.periodEnd}\nStatus: ${run.status}\n\nBase: GHS ${(slip.basePesewas/100).toFixed(2)}\nOvertime: GHS ${(slip.overtimePesewas/100).toFixed(2)}\nBonus: GHS ${(slip.bonusPesewas/100).toFixed(2)}\nDeductions: GHS ${(slip.deductionsPesewas/100).toFixed(2)}\nNet pay: GHS ${(slip.netPesewas/100).toFixed(2)}\n\n${slip.note}`})});await this.audit(m,actor,'payslip_email_queued','payslip',id,{notificationId:row.id});return {queued:true};});}
  async performance(from?:string,to?:string){const {start,end}=this.range(from,to);const [staff,activity,records]=await Promise.all([this.db.getRepository(Employee).find(),this.db.getRepository(ProductionJobActivity).findBy({createdAt:Between(new Date(start),new Date(end+'T23:59:59.999Z'))}),this.listAttendance(start,end)]);return staff.map(e=>{const mine=activity.filter(a=>e.email&&a.actor.toLowerCase()===e.email.toLowerCase()),shifts=records.filter(r=>r.employeeId===e.id&&['present','late'].includes(r.status)),days=new Set(shifts.map(r=>r.workDate)).size,moves=mine.filter(a=>a.type==='stage_change').length;return {employeeId:e.id,name:e.fullName,department:e.department,jobTitle:e.jobTitle,daysPresent:days,lateDays:new Set(shifts.filter(r=>r.status==='late').map(r=>r.workDate)).size,hoursWorked:Math.round(shifts.reduce((s,r)=>s+r.minutesWorked,0)/6)/10,jobsTouched:new Set(mine.map(a=>a.jobId)).size,stageMoves:moves,notesLogged:mine.filter(a=>a.type==='note').length,movesPerDay:days?Math.round(moves/days*10)/10:0};});}
}
